"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](peach)\
$os\
[](bg:rosewater fg:peach)\
$directory\
[](fg:rosewater bg:base)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$conda\
[](fg:base bg:peach)\
$docker_context\
[](bg:rosewater fg:peach)\
$time\
[](fg:rosewater) 
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"


[os]
disabled = false
style = "bg:peach fg:base"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Raspbian = "󰐿"
Macos = ""
Linux = "󰌽"
Android = ""

[directory]
home_symbol = ""
style = "fg:base bg:rosewater"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:base"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:base"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[conda]
symbol = " "
style = "bg:base"
ignore_base = false
format = '[$symbol ($environment) ]($style)'

[docker_context]
symbol = ""
style = "bg:mantle"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
use_12hr = true
time_format = "%I:%M %p"
style = "fg:base bg:rosewater"
format = '[[  $time ](fg:base bg:rosewater)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'